apiVersion: v1
kind: Deployment
metadata: 
 name: java-app
spec:
 replicas: 2
 selector:
  matchLables:
   app: java
 template:
  metadata:
   labels:
    app: java
  spec:
   containers:
    - name: java-container
      image: shruthioli/my-java-app:latest
      ports:
        - containerport: 8080

